[workspace]
resolver = "2"
members = [
    "packages/zkvm", 
    "packages/zkvm-host", 
    "packages/zkvm-core", 
    "packages/zkvm-test"
]

[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
