[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
eth-rpc-url = "http://127.0.0.1:8545"
private_key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
fs_permissions = [{ access = "read-write", path = "./"}]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
