[package]
name = "zkvm-core"
version = "0.1.0"
edition = "2021"

[dependencies]
k256 = { version = "=0.13.1", features = ["arithmetic", "serde", "expose-field", "std", "ecdsa"], default_features = false }
