// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated

pragma solidity ^0.8.20;

library ImageID {
    bytes32 public constant ECDSA_VERIFY_ID =
        bytes32(0x1a0f9afa8cc9df1e4f2a08f58a574e1dc355da3d293dbac707262b256a1d0958);
    bytes32 public constant OWNER_VERIFY_ID =
        bytes32(0x58bff4de70f26531abd8e39d334099b0205df8576333defe627bd2cdb8741b23);
}
